# 测试场景元数据配置文件模板
# 每个测试场景都需要一个metadata.yaml文件来描述场景的基本信息

# 场景名称（必填）
# 📖 说明：场景的唯一标识符，建议使用简洁的英文名称
# 🎯 用途：在日志、报告和CLI中显示
name: "template_scenario"

# 场景描述（必填）
# 📖 说明：详细描述场景的用途、目标和测试内容
# 💡 建议：包含测试目标、预期结果和关键配置信息
description: "场景描述 - 说明这个场景的用途和目标"

# 版本号（可选）
# 📖 说明：场景配置的版本号，用于跟踪配置变更
version: "1.0"

# 场景标签（可选）
# 📖 说明：场景分类标签，用于过滤和分组
# 🎯 用途：可通过scenarios.yaml中的filters配置进行筛选
# 💡 常用标签：["performance", "baseline", "stress", "experimental", "production"]
tags: ["template", "example"]

# 预估执行时间（可选，单位：秒）
# 📖 说明：场景完整执行的预期时间，包括部署、测试和清理
# 🎯 用途：用于执行计划和进度预估
# ⚙️  建议：保守估计，实际时间可能因环境而异
estimated_duration: 1800  # 30分钟

# 场景依赖（可选）
# 📖 说明：此场景依赖的其他场景，系统会确保依赖场景先执行
# 🎯 用途：构建场景间的执行顺序关系
# ⚠️  注意：避免循环依赖，系统会检测并报错
dependencies: []

# 资源要求（可选）
# 📖 说明：场景执行所需的最小硬件资源
# 🎯 用途：系统启动前验证资源充足性
resource_requirements:
  # 最小GPU内存要求
  # 📖 格式：支持 "24GB", "48G", "1TB" 等格式
  min_gpu_memory: "24GB"

  # 最少节点数
  # 📖 说明：场景执行需要的最小节点数量
  min_nodes: 2

  # 最小系统内存（GB）
  # 📖 说明：每个节点所需的最小系统内存
  min_memory_gb: 32

# 作者信息（可选）
# 📖 说明：场景配置的创建者或维护团队
author: "测试团队"

# 创建日期（可选）
# 📖 格式：YYYY-MM-DD
created: "2024-09-06"

# 💡 配置说明：
# 1. 必填字段：name, description
# 2. 场景名称要求唯一，建议使用语义化命名
# 3. estimated_duration用于进度估算，建议实测后更新
# 4. 资源要求会在执行前进行验证，确保环境满足要求
# 5. 标签系统支持复杂的场景筛选和分组功能